Cisco-Firewall233: 
  nodename: Cisco-Firewall233
  hostname: 10.151.71.146
  description: Cisco-Firewall233
  tags: 'routers,hardware'
Juniper-0010-Switch39: 
  nodename: Juniper-0010-Switch39
  hostname: 10.138.153.116
  description: Juniper-0010-Switch39
  tags: 'routers,hardware'
Juniper-2232-Router479: 
  nodename: Juniper-2232-Router479
  hostname: 10.68.170.9
  description: Juniper-2232-Router479
  tags: 'routers,hardware'
Cisco-2232-Router100: 
  nodename: Cisco-2232-Router100
  hostname: 10.179.192.193
  description: Cisco-2232-Router100
  tags: 'routers,hardware'
Cisco-0010-Switch398: 
  nodename: Cisco-0010-Switch398
  hostname: 10.199.48.230
  description: Cisco-0010-Switch398
  tags: 'routers,hardware'
Cisco-2202-Router199: 
  nodename: Cisco-2202-Router199
  hostname: 10.4.210.42
  description: Cisco-2202-Router199
  tags: 'routers,hardware'
Juniper-2232-Router20: 
  nodename: Juniper-2232-Router20
  hostname: 10.121.47.205
  description: Juniper-2232-Router20
  tags: 'routers,hardware'
Juniper-2202-Router81: 
  nodename: Juniper-2202-Router81
  hostname: 10.249.91.66
  description: Juniper-2202-Router81
  tags: 'routers,hardware'
Cisco-2202-Router12: 
  nodename: Cisco-2202-Router12
  hostname: 10.248.235.230
  description: Cisco-2202-Router12
  tags: 'routers,hardware'
Juniper-Firewall168: 
  nodename: Juniper-Firewall168
  hostname: 10.154.202.150
  description: Juniper-Firewall168
  tags: 'routers,hardware'
Cisco-0010-Switch472: 
  nodename: Cisco-0010-Switch472
  hostname: 10.129.233.42
  description: Cisco-0010-Switch472
  tags: 'routers,hardware'
Juniper-0010-Switch73: 
  nodename: Juniper-0010-Switch73
  hostname: 10.212.252.47
  description: Juniper-0010-Switch73
  tags: 'routers,hardware'
Cisco-0010-Switch428: 
  nodename: Cisco-0010-Switch428
  hostname: 10.27.255.111
  description: Cisco-0010-Switch428
  tags: 'routers,hardware'
Cisco-Firewall38: 
  nodename: Cisco-Firewall38
  hostname: 10.109.149.240
  description: Cisco-Firewall38
  tags: 'routers,hardware'
Juniper-0010-Switch377: 
  nodename: Juniper-0010-Switch377
  hostname: 10.93.240.194
  description: Juniper-0010-Switch377
  tags: 'routers,hardware'
TEXAS-372-Win64-Application:
  nodename: TEXAS-372-Win64-Application
  hostname: 10.214.89.76
  description: TEXAS-372-Win64-Application
  tags: 'servers'
CALIFORNIA-16-Linux-Database:
  nodename: CALIFORNIA-16-Linux-Database
  hostname: 10.158.241.113
  description: CALIFORNIA-16-Linux-Database
  tags: 'servers'
PARIS-DR-129-Win64-Application:
  nodename: PARIS-DR-129-Win64-Application
  hostname: 10.131.120.99
  description: PARIS-DR-129-Win64-Application
  tags: 'servers'
PARIS-311-Win64-Server:
  nodename: PARIS-311-Win64-Server
  hostname: 10.111.56.66
  description: PARIS-311-Win64-Server
  tags: 'servers'
FRANKFURT-270-Linux-Application:
  nodename: FRANKFURT-270-Linux-Application
  hostname: 10.195.164.37
  description: FRANKFURT-270-Linux-Application
  tags: 'servers'
DUBLIN-386-Linux-File Storage:
  nodename: DUBLIN-386-Linux-File Storage
  hostname: 10.67.220.114
  description: DUBLIN-386-Linux-File Storage
  tags: 'servers'


